// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // 웹용 Firebase 설정 (임시)
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:123456789012:web:abcdefghijklmnop',
    messagingSenderId: '123456789012',
    projectId: 'moim-money-flutter',
    authDomain: 'moim-money-flutter.firebaseapp.com',
    storageBucket: 'moim-money-flutter.appspot.com',
    measurementId: 'G-XXXXXXXXXX',
  );

  // Android용 Firebase 설정
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIQb-B-zq_qR5jAPG8d3FrGsP2WRBjuy0',
    appId: '1:843936966866:android:1dfbc1651615396370a50b',
    messagingSenderId: '843936966866',
    projectId: 'moim-money-flutter',
    storageBucket: 'moim-money-flutter.firebasestorage.app',
  );

  // iOS용 Firebase 설정 (임시)
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:123456789012:ios:abcdefghijklmnop',
    messagingSenderId: '123456789012',
    projectId: 'moim-money-flutter',
    storageBucket: 'moim-money-flutter.appspot.com',
    iosBundleId: 'com.example.moimMoneyFlutter',
  );

  // macOS용 Firebase 설정 (임시)
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:123456789012:ios:abcdefghijklmnop',
    messagingSenderId: '123456789012',
    projectId: 'moim-money-flutter',
    storageBucket: 'moim-money-flutter.appspot.com',
    iosBundleId: 'com.example.moimMoneyFlutter',
  );

  // Windows용 Firebase 설정 (임시)
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:123456789012:web:abcdefghijklmnop',
    messagingSenderId: '123456789012',
    projectId: 'moim-money-flutter',
    authDomain: 'moim-money-flutter.firebaseapp.com',
    storageBucket: 'moim-money-flutter.appspot.com',
  );
}
